// Copyright © 2021-2023 The Gomon Project.

// Code generated by go generate. DO NOT EDIT.

package main

import (
	"os"
)

var (
	// Srcpath to strip from source file path in log messages.
	Srcpath = "/Users/keefe/Developer/gomon/grafana-plugins/gomon-datasource"

	// module identifies the import package path for this module.
	module = "github.com/zosmac/gomon-datasource"

	// executable identifies the full command path.
	executable, _ = os.Executable()

	// buildDate sets the build date for the command.
	buildDate = func() string {
		info, _ := os.Stat(executable)
		return info.ModTime().UTC().Format("2006-01-02 15:04:05 UTC")
	}()

	// vmmp is "Version, Major, Minor, Patch"
	vmmp = "v2.0.0-278acf5a5fa5"

	// Dependencies import paths and versions
	// github.com/apache/arrow/go/arrow v0.0.0-20211112161151-bc219186db40
	// github.com/beorn7/perks v1.0.1
	// github.com/cespare/xxhash/v2 v2.1.2
	// github.com/cheekybits/genny v1.0.0
	// github.com/davecgh/go-spew v1.1.1
	// github.com/fatih/color v1.7.0
	// github.com/golang/protobuf v1.5.2
	// github.com/golang/snappy v0.0.3
	// github.com/google/flatbuffers v2.0.0+incompatible
	// github.com/google/go-cmp v0.5.7
	// github.com/grafana/grafana-plugin-sdk-go v0.140.0
	// github.com/grpc-ecosystem/go-grpc-middleware v1.3.0
	// github.com/grpc-ecosystem/go-grpc-prometheus v1.2.0
	// github.com/hashicorp/go-hclog v0.14.1
	// github.com/hashicorp/go-plugin v1.4.3
	// github.com/hashicorp/yamux v0.0.0-20181012175058-2f1d1f20f75d
	// github.com/jhump/protoreflect v1.6.0
	// github.com/json-iterator/go v1.1.12
	// github.com/klauspost/compress v1.13.1
	// github.com/mattetti/filebuffer v1.0.1
	// github.com/mattn/go-colorable v0.1.4
	// github.com/mattn/go-isatty v0.0.10
	// github.com/mattn/go-runewidth v0.0.9
	// github.com/matttproud/golang_protobuf_extensions v1.0.1
	// github.com/mitchellh/go-testing-interface v1.0.0
	// github.com/mitchellh/reflectwalk v1.0.2
	// github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
	// github.com/modern-go/reflect2 v1.0.2
	// github.com/oklog/run v1.0.0
	// github.com/olekukonko/tablewriter v0.0.5
	// github.com/pierrec/lz4/v4 v4.1.8
	// github.com/pmezard/go-difflib v1.0.0
	// github.com/prometheus/client_golang v1.12.1
	// github.com/prometheus/client_model v0.2.0
	// github.com/prometheus/common v0.32.1
	// github.com/prometheus/procfs v0.7.3
	// github.com/stretchr/testify v1.7.2
	// golang.org/x/exp v0.0.0-20200224162631-6cc2880d07d6
	// golang.org/x/net v0.0.0-20210614182718-04defd469f4e
	// golang.org/x/sys v0.0.0-20220114195835-da31bd327af9
	// golang.org/x/text v0.3.6
	// golang.org/x/xerrors v0.0.0-20200804184101-5ec99f83aff1
	// gonum.org/v1/gonum v0.9.3
	// google.golang.org/genproto v0.0.0-20210630183607-d20f26d13c79
	// google.golang.org/grpc v1.41.0
	// google.golang.org/protobuf v1.27.1
	// gopkg.in/yaml.v3 v3.0.1
)
